env:
  browser: true
extends: 'eslint:recommended'
# yay, comments!
globals:
  angular: true
  _: true
  $: true
  ansi_up: true
  c3: true
  d3: true
  jsyaml: true
  hawtioPluginLoader: true
  moment: true
  require: true
  URI: true
  Logger: true
  LabelSelector: true
  Messenger: true
rules:
  accessor-pairs: error
  array-bracket-spacing: 'off'
  array-callback-return: error
  arrow-body-style: error
  arrow-parens: error
  arrow-spacing: error
  block-scoped-var: error
  block-spacing: 'off'
  brace-style: 'off'
  callback-return: 'off'
  camelcase: 'off'
  class-methods-use-this: error
  comma-dangle: 'off'
  comma-spacing: 'off'
  comma-style:
    - error
    - last
  complexity: 'off'
  computed-property-spacing:
    - error
    - never
  consistent-return: 'off'
  consistent-this: 'off'
  curly: error
  default-case: 'off'
  dot-location:
    - error
    - property
  dot-notation: 'off'
  eol-last: 'off'
  eqeqeq: error
  func-call-spacing: error
  func-name-matching: error
  func-names: 'off'
  func-style: 'off'
  generator-star-spacing: error
  global-require: error
  guard-for-in: 'off'
  handle-callback-err: error
  id-blacklist: error
  id-length: 'off'
  id-match: error
  indent: 'off'
  init-declarations: 'off'
  jsx-quotes: error
  key-spacing: 'off'
  keyword-spacing: 'off'
  line-comment-position: 'off'
  linebreak-style:
    - error
    - unix
  lines-around-comment: 'off'
  lines-around-directive: 'off'
  max-depth: 'off'
  max-len: 'off'
  max-lines: 'off'
  max-nested-callbacks: error
  max-params: 'off'
  max-statements: 'off'
  max-statements-per-line: 'off'
  multiline-ternary: 'off'
  new-parens: error
  newline-after-var: 'off'
  newline-before-return: 'off'
  newline-per-chained-call: 'off'
  no-alert: error
  no-console: error
  no-array-constructor: error
  no-bitwise: error
  no-caller: error
  no-catch-shadow: 'off'
  no-confusing-arrow: error
  no-continue: 'off'
  no-div-regex: error
  no-duplicate-imports: error
  no-else-return: 'off'
  no-empty:
    - error
    - allowEmptyCatch: true
  no-empty-function: 'off'
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: 'off'
  no-floating-decimal: error
  no-global-assign: error
  no-implicit-globals: 'off'
  no-implied-eval: error
  no-inline-comments: 'off'
  no-inner-declarations:
    - error
    - functions
  no-invalid-this: 'off'
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: 'off'
  no-loop-func: error
  no-magic-numbers: 'off'
  no-mixed-operators: 'off'
  no-mixed-requires: error
  no-multi-spaces: 'off'
  no-multi-str: error
  no-multiple-empty-lines: 'off'
  no-negated-condition: 'off'
  no-nested-ternary: 'off'
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: 'off'
  no-path-concat: error
  no-plusplus: 'off'
  no-process-env: error
  no-process-exit: error
  no-proto: error
  no-prototype-builtins: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: error
  no-script-url: error
  no-self-compare: error
  no-sequences: 'off'
  no-shadow: 'off'
  no-shadow-restricted-names: error
  no-spaced-func: error
  no-sync: error
  no-tabs: 'off'
  no-template-curly-in-string: error
  no-ternary: 'off'
  no-throw-literal: 'off'
  no-trailing-spaces: 'off'
  no-undef-init: error
  no-undefined: 'off'
  no-underscore-dangle: 'off'
  no-unmodified-loop-condition: error
  no-unneeded-ternary: 'off'
  no-unsafe-negation: error
  no-unused-expressions: 'off'
  no-use-before-define: 'off'
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: 'off'
  no-useless-constructor: error
  no-useless-escape: 'off'
  no-useless-rename: error
  no-var: 'off'
  no-void: error
  no-warning-comments: 'off'
  no-whitespace-before-property: error
  no-with: error
  object-curly-newline: 'off'
  object-curly-spacing: 'off'
  object-property-newline: 'off'
  object-shorthand: 'off'
  one-var: 'off'
  one-var-declaration-per-line: 'off'
  operator-assignment: 'off'
  operator-linebreak:
    - error
    - after
  padded-blocks: 'off'
  prefer-arrow-callback: 'off'
  prefer-const: error
  prefer-numeric-literals: error
  prefer-reflect: 'off'
  prefer-rest-params: 'off'
  prefer-spread: 'off'
  prefer-template: 'off'
  quote-props: 'off'
  quotes: 'off'
  radix: 'off'
  require-jsdoc: 'off'
  rest-spread-spacing: error
  semi: 'off'
  semi-spacing: 'off'
  sort-imports: error
  sort-keys: 'off'
  sort-vars: 'off'
  space-before-blocks: 'off'
  space-before-function-paren: 'off'
  space-in-parens: 'off'
  space-infix-ops: 'off'
  space-unary-ops: error
  spaced-comment: 'off'
  strict: 'off'
  symbol-description: error
  template-curly-spacing: error
  unicode-bom:
    - error
    - never
  valid-jsdoc: 'off'
  vars-on-top: 'off'
  wrap-regex: 'off'
  yield-star-spacing: error
  yoda: 'off'
